@startuml
'https://plantuml.com/class-diagram

class Survey {
    - long surveyId
    - SurveyTemplate template
    '-String[] answers
}

abstract class Question {
- long questionId
 -String statement
 - boolean required
}
class OpenQuestion extends Question {
 -String answer
}

class MultipleOptionQuestion extends Question {
    -String[] answerOptions
    -int answerIdx
}

class DateQuestion extends Question {
    Date theDate
}


class Section {
 - long sectionId
 - string name
 - Question[] questions
}

class SurveyTemplate {
  - long surveyTemplateId
  - Section[] sections
}

SurveyTemplate -* Section
Section -* Question
Survey *- SurveyTemplate

@enduml